### ISSUE TITLE
Republish extension?

### ISSUE THREAD

**Issue by multimeric** [downforacross/downloadacross#8]
Hi, it looks like this extension got pulled off the Chrome Store. Do you need any help getting it published again?

**Comment by stevenhao** [comment]
Ah yeah, I never got around to trying again after it got pulled off. I think the stated reason was something trivial with the metadata & keywords I listed on the web store, so it's definitely worth another shot. I'll update this github issue once I've tried again!

Thanks for opening this issue!

**Comment by stevenhao** [comment]
Update: Just submitted an updated package & description to the web store. The review may take a while.

**Comment by multimeric** [comment]
Excellent! I just went through the review process and it took me about 2 weeks from submission to acceptance so hopefully you have better luck than me.

**Comment by stevenhao** [comment]
that was fast, https://chrome.google.com/webstore/detail/idbdbedhgabnbjfjecpflfomnklpllen
